# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './modules/mainWindow.ui'
#
# Created: Wed Nov 28 16:06:48 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 728)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pyrrhic REE", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbReg = QtGui.QGroupBox(self.centralwidget)
        self.gbReg.setTitle(QtGui.QApplication.translate("MainWindow", "Regular Expression Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.gbReg.setObjectName(_fromUtf8("gbReg"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbReg)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tedReg = QtGui.QTextEdit(self.gbReg)
        self.tedReg.setObjectName(_fromUtf8("tedReg"))
        self.horizontalLayout_2.addWidget(self.tedReg)
        self.verticalLayout.addWidget(self.gbReg)
        self.gbFlags = QtGui.QGroupBox(self.centralwidget)
        self.gbFlags.setMinimumSize(QtCore.QSize(0, 60))
        self.gbFlags.setTitle(QtGui.QApplication.translate("MainWindow", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.gbFlags.setObjectName(_fromUtf8("gbFlags"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbFlags)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkCase = QtGui.QCheckBox(self.gbFlags)
        self.chkCase.setText(QtGui.QApplication.translate("MainWindow", "Ignore Case", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCase.setObjectName(_fromUtf8("chkCase"))
        self.horizontalLayout.addWidget(self.chkCase)
        self.chkMulti = QtGui.QCheckBox(self.gbFlags)
        self.chkMulti.setText(QtGui.QApplication.translate("MainWindow", "Multi Line", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMulti.setObjectName(_fromUtf8("chkMulti"))
        self.horizontalLayout.addWidget(self.chkMulti)
        self.chkDot = QtGui.QCheckBox(self.gbFlags)
        self.chkDot.setText(QtGui.QApplication.translate("MainWindow", "Dot All", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDot.setObjectName(_fromUtf8("chkDot"))
        self.horizontalLayout.addWidget(self.chkDot)
        self.chkVerbose = QtGui.QCheckBox(self.gbFlags)
        self.chkVerbose.setText(QtGui.QApplication.translate("MainWindow", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.chkVerbose.setObjectName(_fromUtf8("chkVerbose"))
        self.horizontalLayout.addWidget(self.chkVerbose)
        self.chkLocale = QtGui.QCheckBox(self.gbFlags)
        self.chkLocale.setText(QtGui.QApplication.translate("MainWindow", "Locale", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLocale.setObjectName(_fromUtf8("chkLocale"))
        self.horizontalLayout.addWidget(self.chkLocale)
        self.chkUnicode = QtGui.QCheckBox(self.gbFlags)
        self.chkUnicode.setText(QtGui.QApplication.translate("MainWindow", "Unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUnicode.setObjectName(_fromUtf8("chkUnicode"))
        self.horizontalLayout.addWidget(self.chkUnicode)
        self.verticalLayout.addWidget(self.gbFlags)
        self.gbString = QtGui.QGroupBox(self.centralwidget)
        self.gbString.setTitle(QtGui.QApplication.translate("MainWindow", "Search String", None, QtGui.QApplication.UnicodeUTF8))
        self.gbString.setObjectName(_fromUtf8("gbString"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gbString)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tedString = QtGui.QTextEdit(self.gbString)
        self.tedString.setObjectName(_fromUtf8("tedString"))
        self.horizontalLayout_3.addWidget(self.tedString)
        self.verticalLayout.addWidget(self.gbString)
        self.gbResults = QtGui.QGroupBox(self.centralwidget)
        self.gbResults.setTitle(QtGui.QApplication.translate("MainWindow", "Match", None, QtGui.QApplication.UnicodeUTF8))
        self.gbResults.setObjectName(_fromUtf8("gbResults"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbResults)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tedMatch = QtGui.QTextEdit(self.gbResults)
        self.tedMatch.setReadOnly(True)
        self.tedMatch.setObjectName(_fromUtf8("tedMatch"))
        self.horizontalLayout_4.addWidget(self.tedMatch)
        self.verticalLayout.addWidget(self.gbResults)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegex_Reference_Guide = QtGui.QAction(MainWindow)
        self.actionRegex_Reference_Guide.setText(QtGui.QApplication.translate("MainWindow", "Regex Reference Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegex_Reference_Guide.setObjectName(_fromUtf8("actionRegex_Reference_Guide"))
        self.actionRegex_Library = QtGui.QAction(MainWindow)
        self.actionRegex_Library.setText(QtGui.QApplication.translate("MainWindow", "Regex Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegex_Library.setObjectName(_fromUtf8("actionRegex_Library"))
        self.actionPython_Regex_Help = QtGui.QAction(MainWindow)
        self.actionPython_Regex_Help.setText(QtGui.QApplication.translate("MainWindow", "Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython_Regex_Help.setObjectName(_fromUtf8("actionPython_Regex_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionShow_Variables = QtGui.QAction(MainWindow)
        self.actionShow_Variables.setText(QtGui.QApplication.translate("MainWindow", "Show Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Variables.setObjectName(_fromUtf8("actionShow_Variables"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuFile.addAction(self.actionShow_Variables)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionRegex_Reference_Guide)
        self.menuHelp.addAction(self.actionRegex_Library)
        self.menuHelp.addAction(self.actionPython_Regex_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

