# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './modules/mainWindow.ui'
#
# Created: Fri Dec 28 14:49:24 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 665)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pyrrhic REE", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbReg = QtGui.QGroupBox(self.centralwidget)
        self.gbReg.setTitle(QtGui.QApplication.translate("MainWindow", "Regular Expression Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.gbReg.setObjectName(_fromUtf8("gbReg"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbReg)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tedReg = QtGui.QTextEdit(self.gbReg)
        self.tedReg.setAutoFillBackground(False)
        self.tedReg.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tedReg.setFrameShadow(QtGui.QFrame.Sunken)
        self.tedReg.setObjectName(_fromUtf8("tedReg"))
        self.horizontalLayout_2.addWidget(self.tedReg)
        self.verticalLayout_2.addWidget(self.gbReg)
        self.gbFlagButtons = QtGui.QGroupBox(self.centralwidget)
        self.gbFlagButtons.setTitle(_fromUtf8(""))
        self.gbFlagButtons.setObjectName(_fromUtf8("gbFlagButtons"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.gbFlagButtons)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.gbFlags = QtGui.QGroupBox(self.gbFlagButtons)
        self.gbFlags.setMinimumSize(QtCore.QSize(0, 60))
        self.gbFlags.setTitle(QtGui.QApplication.translate("MainWindow", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.gbFlags.setObjectName(_fromUtf8("gbFlags"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbFlags)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.chkCase = QtGui.QCheckBox(self.gbFlags)
        self.chkCase.setToolTip(QtGui.QApplication.translate("MainWindow", "Perform case-insensitive matching", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCase.setText(QtGui.QApplication.translate("MainWindow", "Ignore Case", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCase.setObjectName(_fromUtf8("chkCase"))
        self.horizontalLayout.addWidget(self.chkCase)
        self.chkMulti = QtGui.QCheckBox(self.gbFlags)
        self.chkMulti.setToolTip(QtGui.QApplication.translate("MainWindow", "^ matches at the beginning of the string and at the beginning of each line within the string, immediately following each newline. Similarly, the $ metacharacter matches either at the end of the string and at the end of each line (immediately preceding each newline).", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMulti.setText(QtGui.QApplication.translate("MainWindow", "Multi Line", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMulti.setObjectName(_fromUtf8("chkMulti"))
        self.horizontalLayout.addWidget(self.chkMulti)
        self.chkDot = QtGui.QCheckBox(self.gbFlags)
        self.chkDot.setToolTip(QtGui.QApplication.translate("MainWindow", "Makes the \'.\' special character match any character at all, including a newline; without this flag, \'.\' will match anything except a newline.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDot.setText(QtGui.QApplication.translate("MainWindow", "Dot All", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDot.setObjectName(_fromUtf8("chkDot"))
        self.horizontalLayout.addWidget(self.chkDot)
        self.chkVerbose = QtGui.QCheckBox(self.gbFlags)
        self.chkVerbose.setToolTip(QtGui.QApplication.translate("MainWindow", "This flag allows you to write regular expressions that are more readable by granting you more flexibility in how you can format them. When this flag has been specified, whitespace within the RE string is ignored, except when the whitespace is in a character class or preceded by an unescaped backslash; this lets you organize and indent the RE more clearly. This flag also lets you put comments within a RE that will be ignored by the engine; comments are marked by a \'#\' that’s neither in a character class or preceded by an unescaped backslash.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkVerbose.setText(QtGui.QApplication.translate("MainWindow", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.chkVerbose.setObjectName(_fromUtf8("chkVerbose"))
        self.horizontalLayout.addWidget(self.chkVerbose)
        self.chkLocale = QtGui.QCheckBox(self.gbFlags)
        self.chkLocale.setToolTip(QtGui.QApplication.translate("MainWindow", "Make w, W, b, and B, dependent on the current locale.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLocale.setText(QtGui.QApplication.translate("MainWindow", "Locale", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLocale.setObjectName(_fromUtf8("chkLocale"))
        self.horizontalLayout.addWidget(self.chkLocale)
        self.chkAscii = QtGui.QCheckBox(self.gbFlags)
        self.chkAscii.setToolTip(QtGui.QApplication.translate("MainWindow", "Make w, W, b, B, s and S perform ASCII-only matching instead of full Unicode matching. This is only meaningful for Unicode patterns, and is ignored for byte patterns.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAscii.setText(QtGui.QApplication.translate("MainWindow", "Ascii", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAscii.setObjectName(_fromUtf8("chkAscii"))
        self.horizontalLayout.addWidget(self.chkAscii)
        self.horizontalLayout_8.addWidget(self.gbFlags)
        self.gbButtons = QtGui.QGroupBox(self.gbFlagButtons)
        self.gbButtons.setTitle(_fromUtf8(""))
        self.gbButtons.setObjectName(_fromUtf8("gbButtons"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gbButtons)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pbPause = QtGui.QPushButton(self.gbButtons)
        self.pbPause.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pbPause.setObjectName(_fromUtf8("pbPause"))
        self.horizontalLayout_7.addWidget(self.pbPause)
        self.pbExamin = QtGui.QPushButton(self.gbButtons)
        self.pbExamin.setText(QtGui.QApplication.translate("MainWindow", "Examine", None, QtGui.QApplication.UnicodeUTF8))
        self.pbExamin.setObjectName(_fromUtf8("pbExamin"))
        self.horizontalLayout_7.addWidget(self.pbExamin)
        self.horizontalLayout_8.addWidget(self.gbButtons)
        self.verticalLayout_2.addWidget(self.gbFlagButtons)
        self.tabStringRep = QtGui.QTabWidget(self.centralwidget)
        self.tabStringRep.setObjectName(_fromUtf8("tabStringRep"))
        self.tabString = QtGui.QWidget()
        self.tabString.setObjectName(_fromUtf8("tabString"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabString)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tedString = QtGui.QTextEdit(self.tabString)
        self.tedString.setObjectName(_fromUtf8("tedString"))
        self.verticalLayout_3.addWidget(self.tedString)
        self.tabStringRep.addTab(self.tabString, _fromUtf8(""))
        self.tabRepStr = QtGui.QWidget()
        self.tabRepStr.setObjectName(_fromUtf8("tabRepStr"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabRepStr)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tedReplace = QtGui.QTextEdit(self.tabRepStr)
        self.tedReplace.setObjectName(_fromUtf8("tedReplace"))
        self.verticalLayout.addWidget(self.tedReplace)
        self.tabStringRep.addTab(self.tabRepStr, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabStringRep)
        self.tabResults = QtGui.QTabWidget(self.centralwidget)
        self.tabResults.setObjectName(_fromUtf8("tabResults"))
        self.tabMatch = QtGui.QWidget()
        self.tabMatch.setObjectName(_fromUtf8("tabMatch"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tabMatch)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tebMatch = QtGui.QTextBrowser(self.tabMatch)
        self.tebMatch.setObjectName(_fromUtf8("tebMatch"))
        self.horizontalLayout_4.addWidget(self.tebMatch)
        self.tabResults.addTab(self.tabMatch, _fromUtf8(""))
        self.tabMatchAll = QtGui.QWidget()
        self.tabMatchAll.setObjectName(_fromUtf8("tabMatchAll"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tabMatchAll)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tebMatchAll = QtGui.QTextBrowser(self.tabMatchAll)
        self.tebMatchAll.setObjectName(_fromUtf8("tebMatchAll"))
        self.horizontalLayout_5.addWidget(self.tebMatchAll)
        self.tabResults.addTab(self.tabMatchAll, _fromUtf8(""))
        self.tabGroup = QtGui.QWidget()
        self.tabGroup.setObjectName(_fromUtf8("tabGroup"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tabGroup)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tebGroup = QtGui.QTextBrowser(self.tabGroup)
        self.tebGroup.setObjectName(_fromUtf8("tebGroup"))
        self.horizontalLayout_6.addWidget(self.tebGroup)
        self.tabResults.addTab(self.tabGroup, _fromUtf8(""))
        self.tabRep1 = QtGui.QWidget()
        self.tabRep1.setObjectName(_fromUtf8("tabRep1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabRep1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tebRep1 = QtGui.QTextBrowser(self.tabRep1)
        self.tebRep1.setObjectName(_fromUtf8("tebRep1"))
        self.verticalLayout_4.addWidget(self.tebRep1)
        self.tabResults.addTab(self.tabRep1, _fromUtf8(""))
        self.tabRepAll = QtGui.QWidget()
        self.tabRepAll.setObjectName(_fromUtf8("tabRepAll"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabRepAll)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tebRepAll = QtGui.QTextBrowser(self.tabRepAll)
        self.tebRepAll.setObjectName(_fromUtf8("tebRepAll"))
        self.verticalLayout_5.addWidget(self.tebRepAll)
        self.tabResults.addTab(self.tabRepAll, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabResults)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegex_Reference_Guide = QtGui.QAction(MainWindow)
        self.actionRegex_Reference_Guide.setText(QtGui.QApplication.translate("MainWindow", "Regex Reference Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegex_Reference_Guide.setObjectName(_fromUtf8("actionRegex_Reference_Guide"))
        self.actionRegex_Library = QtGui.QAction(MainWindow)
        self.actionRegex_Library.setText(QtGui.QApplication.translate("MainWindow", "Regex Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegex_Library.setObjectName(_fromUtf8("actionRegex_Library"))
        self.actionPython_Regex_Help = QtGui.QAction(MainWindow)
        self.actionPython_Regex_Help.setText(QtGui.QApplication.translate("MainWindow", "Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython_Regex_Help.setObjectName(_fromUtf8("actionPython_Regex_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionShow_Variables = QtGui.QAction(MainWindow)
        self.actionShow_Variables.setText(QtGui.QApplication.translate("MainWindow", "Show Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Variables.setObjectName(_fromUtf8("actionShow_Variables"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionImport_URL = QtGui.QAction(MainWindow)
        self.actionImport_URL.setText(QtGui.QApplication.translate("MainWindow", "Import URL", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_URL.setObjectName(_fromUtf8("actionImport_URL"))
        self.actionImport_File = QtGui.QAction(MainWindow)
        self.actionImport_File.setText(QtGui.QApplication.translate("MainWindow", "Import File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_File.setObjectName(_fromUtf8("actionImport_File"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_URL)
        self.menuFile.addAction(self.actionImport_File)
        self.menuHelp.addAction(self.actionRegex_Reference_Guide)
        self.menuHelp.addAction(self.actionRegex_Library)
        self.menuHelp.addAction(self.actionPython_Regex_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabStringRep.setCurrentIndex(0)
        self.tabResults.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabStringRep.setTabText(self.tabStringRep.indexOf(self.tabString), QtGui.QApplication.translate("MainWindow", "Search String", None, QtGui.QApplication.UnicodeUTF8))
        self.tabStringRep.setTabText(self.tabStringRep.indexOf(self.tabRepStr), QtGui.QApplication.translate("MainWindow", "Replace String", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResults.setTabText(self.tabResults.indexOf(self.tabMatch), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResults.setTabText(self.tabResults.indexOf(self.tabMatchAll), QtGui.QApplication.translate("MainWindow", "Find All", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResults.setTabText(self.tabResults.indexOf(self.tabGroup), QtGui.QApplication.translate("MainWindow", "Group", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResults.setTabText(self.tabResults.indexOf(self.tabRep1), QtGui.QApplication.translate("MainWindow", "Replace First", None, QtGui.QApplication.UnicodeUTF8))
        self.tabResults.setTabText(self.tabResults.indexOf(self.tabRepAll), QtGui.QApplication.translate("MainWindow", "Replace All", None, QtGui.QApplication.UnicodeUTF8))

