# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Tue Nov 27 17:23:28 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.8
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 728)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbReg = QtGui.QGroupBox(self.centralwidget)
        self.gbReg.setObjectName("gbReg")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.gbReg)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tedReg = QtGui.QTextEdit(self.gbReg)
        self.tedReg.setObjectName("tedReg")
        self.horizontalLayout_2.addWidget(self.tedReg)
        self.verticalLayout.addWidget(self.gbReg)
        self.gbFlags = QtGui.QGroupBox(self.centralwidget)
        self.gbFlags.setMinimumSize(QtCore.QSize(0, 60))
        self.gbFlags.setObjectName("gbFlags")
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbFlags)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkCase = QtGui.QCheckBox(self.gbFlags)
        self.chkCase.setObjectName("chkCase")
        self.horizontalLayout.addWidget(self.chkCase)
        self.chkMulti = QtGui.QCheckBox(self.gbFlags)
        self.chkMulti.setObjectName("chkMulti")
        self.horizontalLayout.addWidget(self.chkMulti)
        self.chkDot = QtGui.QCheckBox(self.gbFlags)
        self.chkDot.setObjectName("chkDot")
        self.horizontalLayout.addWidget(self.chkDot)
        self.chkVerbose = QtGui.QCheckBox(self.gbFlags)
        self.chkVerbose.setObjectName("chkVerbose")
        self.horizontalLayout.addWidget(self.chkVerbose)
        self.chkLocale = QtGui.QCheckBox(self.gbFlags)
        self.chkLocale.setObjectName("chkLocale")
        self.horizontalLayout.addWidget(self.chkLocale)
        self.chkUnicode = QtGui.QCheckBox(self.gbFlags)
        self.chkUnicode.setObjectName("chkUnicode")
        self.horizontalLayout.addWidget(self.chkUnicode)
        self.verticalLayout.addWidget(self.gbFlags)
        self.gbString = QtGui.QGroupBox(self.centralwidget)
        self.gbString.setObjectName("gbString")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gbString)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tedString = QtGui.QTextEdit(self.gbString)
        self.tedString.setObjectName("tedString")
        self.horizontalLayout_3.addWidget(self.tedString)
        self.verticalLayout.addWidget(self.gbString)
        self.gbResults = QtGui.QGroupBox(self.centralwidget)
        self.gbResults.setObjectName("gbResults")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbResults)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tedMatch = QtGui.QTextEdit(self.gbResults)
        self.tedMatch.setReadOnly(True)
        self.tedMatch.setObjectName("tedMatch")
        self.horizontalLayout_4.addWidget(self.tedMatch)
        self.verticalLayout.addWidget(self.gbResults)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegex_Reference_Guide = QtGui.QAction(MainWindow)
        self.actionRegex_Reference_Guide.setObjectName("actionRegex_Reference_Guide")
        self.actionRegex_Library = QtGui.QAction(MainWindow)
        self.actionRegex_Library.setObjectName("actionRegex_Library")
        self.actionPython_Regex_Help = QtGui.QAction(MainWindow)
        self.actionPython_Regex_Help.setObjectName("actionPython_Regex_Help")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionShow_Variables = QtGui.QAction(MainWindow)
        self.actionShow_Variables.setObjectName("actionShow_Variables")
        self.menuFile.addAction(self.actionShow_Variables)
        self.menuHelp.addAction(self.actionRegex_Reference_Guide)
        self.menuHelp.addAction(self.actionRegex_Library)
        self.menuHelp.addAction(self.actionPython_Regex_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Pyrrhic REE", None, QtGui.QApplication.UnicodeUTF8))
        self.gbReg.setTitle(QtGui.QApplication.translate("MainWindow", "Regular Expression Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.gbFlags.setTitle(QtGui.QApplication.translate("MainWindow", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCase.setText(QtGui.QApplication.translate("MainWindow", "Ignore Case", None, QtGui.QApplication.UnicodeUTF8))
        self.chkMulti.setText(QtGui.QApplication.translate("MainWindow", "Multi Line", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDot.setText(QtGui.QApplication.translate("MainWindow", "Dot All", None, QtGui.QApplication.UnicodeUTF8))
        self.chkVerbose.setText(QtGui.QApplication.translate("MainWindow", "Verbose", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLocale.setText(QtGui.QApplication.translate("MainWindow", "Locale", None, QtGui.QApplication.UnicodeUTF8))
        self.chkUnicode.setText(QtGui.QApplication.translate("MainWindow", "Unicode", None, QtGui.QApplication.UnicodeUTF8))
        self.gbString.setTitle(QtGui.QApplication.translate("MainWindow", "Search String", None, QtGui.QApplication.UnicodeUTF8))
        self.gbResults.setTitle(QtGui.QApplication.translate("MainWindow", "Match", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegex_Reference_Guide.setText(QtGui.QApplication.translate("MainWindow", "Regex Reference Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegex_Library.setText(QtGui.QApplication.translate("MainWindow", "Regex Library", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPython_Regex_Help.setText(QtGui.QApplication.translate("MainWindow", "Python Regex Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Variables.setText(QtGui.QApplication.translate("MainWindow", "Show Variables", None, QtGui.QApplication.UnicodeUTF8))

